### PR TITLE
z_woa13: Optionally calculate PotT from T

### PR DESCRIPTION
**Pull request by mhrib**
* Optionally calculate potential temperature from in-situ temperature.

If "PTEMP" field is present in CDF_TEMP NetCDF file, do as always.
If NOT present, look for field "TEMP". If present assume it is in-situ temperature, and calculate potential temperature in-line.

### CODE REVIEW

**Comment by mhrib** [comment]
I have also made a Fortran program, that can "merge" WOA18 monthly and quarterly fields + make an (ugly looking) interpolation over land by iterate through missing points and only use (up to) 4 neighbor points. Thereafter z_woa13 can be used...
I can provide the programme as well if you like.

**Comment by abozec** [comment]
sorry for the delay in the response, 
We actually have an alternative old set of functions for pot temp in archive/src, named mod_ppsw.F. 
> grep "PPSW_" archv2data3z.f
     &      PPSW_theta  => theta,
     &      PPSW_p80    => p80
     &              PPSW_p80(0.5*(p(i,j,k)+p(i,j,k+1)), plat(i,j))
     &              PPSW_theta(saln(i,j,k),temp(i,j,k), 0.0,dbar)
>
Would you be willing  to switch your function to these WHOI routines?  This would involve adding mod_ppsw.F to relax/src and updating the Makefile.

and yes please do another pull request for the WOA18 monthly and quarterly field program.
Thanks

**Comment by mhrib** [comment]
Thanks,

I was not aware of this. I will use these instead, test and update with another pull request when done.


rgs

Mads


________________________________

**Comment by mhrib** [comment]
Something went wrong between GIT and me:-(
Now the updates is included within PR #4 TOGETER with the utility program woa18_to_woa13_format.

Hope this is handable for you. Else please speak up.

**Pull request closed without merging**
