### PR TITLE
WOA18 to WOA13 utility program + z_woa13 optionally convert TEMP to PTEMP

### PR DESCRIPTION
**Pull request by mhrib**
1) Utility program to convert WOA18 clim. data to WOA13-a-like ready for z_woa13 utility:
- Merge monthly and seasonally data into one NetCDF file
- Interpolate/extrapolate over land and below sea-bed, which is needed 

2) z_woa13: Calculate PTEMP inline if only TEMP is found in NetCDF files. (update of PR #3) 
- Now using WHOI utilities - mod_ppsw.F - for calculating PTEMP using theta+p80
- Added option ICTYPE=5:
a) inforce stable density stratification (as ICTYPE=3)
b) use salinity dependent Freezing point Tf=-0.054*S (as ICTYPE=4)

### CODE REVIEW

**Comment by mhrib** [comment]
The idea was to update PR #3, but GIT and I am not always best friends:-(
Therefore, #3 is updated here TOGETHER with utility program "woa18_to_woa13_format".

Hope it is ok?

**Comment by abozec** [comment]
I've tested it and it is working well, thanks.
Could you just add the links to the seasonal WOA18 files in the write outs of  woa18_to_woa13_format.f90? it will be clearer for the user to know which files to get it to work. I will merge the request once that is done.

**Comment by mhrib** [comment]
I have updated woa18_to_woa13_format.f90:
* If native WOA18 NetCDF files do not exist in the current directory, it tells exactly which file is missing AND it will also print the USAGE, which includes links to where files can be downloaded.

Think it was something like that you suggested?

**Comment by abozec** [comment]
Yes that is fine, thanks.

**Pull request merged**
